package com.sky.gank.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sky.gank.data.douban.SubjectsBean;
import com.sky.gank.data.meizi.MeizhiBean;

import com.sky.gank.greendao.SubjectsBeanDao;
import com.sky.gank.greendao.MeizhiBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subjectsBeanDaoConfig;
    private final DaoConfig meizhiBeanDaoConfig;

    private final SubjectsBeanDao subjectsBeanDao;
    private final MeizhiBeanDao meizhiBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subjectsBeanDaoConfig = daoConfigMap.get(SubjectsBeanDao.class).clone();
        subjectsBeanDaoConfig.initIdentityScope(type);

        meizhiBeanDaoConfig = daoConfigMap.get(MeizhiBeanDao.class).clone();
        meizhiBeanDaoConfig.initIdentityScope(type);

        subjectsBeanDao = new SubjectsBeanDao(subjectsBeanDaoConfig, this);
        meizhiBeanDao = new MeizhiBeanDao(meizhiBeanDaoConfig, this);

        registerDao(SubjectsBean.class, subjectsBeanDao);
        registerDao(MeizhiBean.class, meizhiBeanDao);
    }
    
    public void clear() {
        subjectsBeanDaoConfig.clearIdentityScope();
        meizhiBeanDaoConfig.clearIdentityScope();
    }

    public SubjectsBeanDao getSubjectsBeanDao() {
        return subjectsBeanDao;
    }

    public MeizhiBeanDao getMeizhiBeanDao() {
        return meizhiBeanDao;
    }

}
