package com.sky.gank.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sky.gank.data.douban.SubjectsBean;

import com.sky.gank.greendao.SubjectsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subjectsBeanDaoConfig;

    private final SubjectsBeanDao subjectsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subjectsBeanDaoConfig = daoConfigMap.get(SubjectsBeanDao.class).clone();
        subjectsBeanDaoConfig.initIdentityScope(type);

        subjectsBeanDao = new SubjectsBeanDao(subjectsBeanDaoConfig, this);

        registerDao(SubjectsBean.class, subjectsBeanDao);
    }
    
    public void clear() {
        subjectsBeanDaoConfig.clearIdentityScope();
    }

    public SubjectsBeanDao getSubjectsBeanDao() {
        return subjectsBeanDao;
    }

}
